<a href="https://colab.research.google.com/github/Pankaj122002/Python/blob/main/Purchase%20Prediction%20And%20Micronumerosity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
purchase = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Customer%20Purchase.csv')

In [5]:
purchase.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [6]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50 non-null     int64
 1   Age          50 non-null     int64
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

In [7]:
purchase.describe()

       Customer ID        Age
count     50.00000  50.000000
mean    1045.50000  54.160000
std       14.57738  25.658161
min     1021.00000  15.000000
25%     1033.25000  30.250000
50%     1045.50000  57.000000
75%     1057.75000  74.000000
max     1070.00000  98.000000

In [8]:
purchase.columns

Index(['Customer ID', 'Age', 'Gender', 'Education', 'Review', 'Purchased'], dtype='object')

In [9]:
y = purchase['Purchased']

In [10]:
X = purchase.drop(['Purchased','Customer ID'],axis=1)

In [11]:
X

    Age  Gender Education   Review
0    30  Female    School  Average
1    68  Female        UG     Poor
2    70  Female        PG     Good
3    72  Female        PG     Good
4    16  Female        UG  Average
5    31  Female    School  Average
6    18    Male    School     Good
7    60  Female    School     Poor
8    65  Female        UG  Average
9    74    Male        UG     Good
10   98  Female        UG     Good
11   74    Male        UG     Good
12   51    Male    School     Poor
13   57  Female    School  Average
14   15    Male        PG     Poor
15   75    Male        UG     Poor
16   59    Male        UG     Poor
17   22  Female        UG     Poor
18   19    Male    School     Good
19   97    Male        PG     Poor
20   57  Female    School  Average
21   32    Male        PG  Average
22   18  Female        PG     Poor
23   96  Female    School     Good
24   16  Female        PG  Average
25   57  Female    School     Good
26   53  Female        PG     Poor
27   69  Female        PG     Poor
28   48    Male    School     Poor
29   83  Female        UG  Average
30   73    Male        UG  Average
31   22  Female    School     Poor
32   92    Male        UG  Average
33   89  Female        PG     Good
34   86    Male    School  Average
35   74    Male    School     Poor
36   34  Female        UG     Good
37   94    Male        PG  Average
38   45  Female    School     Good
39   76    Male        PG     Poor
40   39    Male    School     Good
41   23    Male        PG     Good
42   30  Female        PG     Good
43   27    Male        PG     Poor
44   77  Female        UG  Average
45   61    Male        PG     Poor
46   64  Female        PG     Poor
47   38  Female        PG     Good
48   39  Female        UG     Good
49   25  Female        UG     Good

In [12]:
X.replace({'Review':{'Poor':0,'Average':1,'Good':2}},inplace=True)
X.replace({'Education':{'School':0,'UG':1,'PG':2}},inplace=True)
X.replace({'Gender':{'Male': 0,'Female':1}},inplace=True)

In [13]:
X

    Age  Gender  Education  Review
0    30       1          0       1
1    68       1          1       0
2    70       1          2       2
3    72       1          2       2
4    16       1          1       1
5    31       1          0       1
6    18       0          0       2
7    60       1          0       0
8    65       1          1       1
9    74       0          1       2
10   98       1          1       2
11   74       0          1       2
12   51       0          0       0
13   57       1          0       1
14   15       0          2       0
15   75       0          1       0
16   59       0          1       0
17   22       1          1       0
18   19       0          0       2
19   97       0          2       0
20   57       1          0       1
21   32       0          2       1
22   18       1          2       0
23   96       1          0       2
24   16       1          2       1
25   57       1          0       2
26   53       1          2       0
27   69       1          2       0
28   48       0          0       0
29   83       1          1       1
30   73       0          1       1
31   22       1          0       0
32   92       0          1       1
33   89       1          2       2
34   86       0          0       1
35   74       0          0       0
36   34       1          1       2
37   94       0          2       1
38   45       1          0       2
39   76       0          2       0
40   39       0          0       2
41   23       0          2       2
42   30       1          2       2
43   27       0          2       0
44   77       1          1       1
45   61       0          2       0
46   64       1          2       0
47   38       1          2       2
48   39       1          1       2
49   25       1          1       2

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, random_state=2529)

In [15]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40, 4), (10, 4), (40,), (10,))

In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [17]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes'],
      dtype=object)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [21]:
confusion_matrix(y_test,y_pred)

array([[2, 1],
       [3, 4]])

In [22]:
accuracy_score(y_test,y_pred)

0.6

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          No       0.40      0.67      0.50         3
         Yes       0.80      0.57      0.67         7

    accuracy                           0.60        10
   macro avg       0.60      0.62      0.58        10
weighted avg       0.68      0.60      0.62        10